# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  repo-owner:  # id of input
    description: 'Username of owner for the repo in which this Action is used.'
    required: true
    default: ''
  repo-name:  # id of input
    description: 'The name of the repo in which this Action is used.'
    required: true
    default: ''
  server-name:  # id of input
    description: 'The domain name of the server to setup.'
    required: true
    default: ''
  user-email:  # id of input
    description: 'An email that will be used to request an https certificate.'
    required: true
    default: ''
  server-user:  # id of input
    description: 'The username used to connect to the server.'
    required: true
    default: 'root'
  ssh-key:  # id of input
    description: 'Private ssh key.'
    required: true
    default: ''    
runs:
  using: "composite"
  steps:
  
      - uses: actions/checkout@v4
      
      - name: Add Known Host and SSH Key File
        shell: bash
        run: |
            mkdir .ssh
            #ssh-keyscan ${{ inputs.server-name }} >> .ssh/known_hosts
            echo "value" >> .ssh/known_hosts
            echo "${{ inputs.ssh-key }}" > .ssh/id_rsa

      - name: Dump github context
        shell: bash
        env:
           GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      #- name: Call Remote Init Script
      #   shell: bash
      #  run: ssh -i .ssh/id_rsa ${{ inputs.server-user }}@${{ inputs.server-name }} "bash -s" < init.sh ${{ inputs.repo-owner }} ${{ inputs.repo-name }} ${{ inputs.server-name }} ${{ inputs.user-email }}
        
      #- name: Call Remote Deploy Script
      #   shell: bash
      #  run: ssh -i .ssh/id_rsa ${{ inputs.server-user }}@${{ inputs.server-name }} "bash -s" < deploy.sh ${{ inputs.repo-owner }} ${{ inputs.repo-name }}

