# action.yml
name: 'Deploy Server'
description: 'Setup Ubuntu 22 LTS Server to Host Node Server.'
inputs:
  server-username:  # id of input
    description: 'The username used to connect to the server. Default is "root".'
    required: false
    default: 'root'
  server-host:  # id of input
    description: 'The domain name of the server to setup.'
    required: true
  user-email:  # id of input
    description: 'An email used to request an https certificate using certbot.'
    required: true
  ssh-key:  # id of input
    description: 'Private ssh key.'
    required: true
runs:
  using: "composite"
  steps:
      - uses: actions/checkout@v4
      
      - name: Add Known Host and SSH Key File
        shell: bash
        run: |
            # See: https://maxschmitt.me/posts/github-actions-ssh-key
            mkdir -p /home/runner/.ssh
            ssh-keyscan ${{ inputs.server-host }} >> /home/runner/.ssh/known_hosts
            echo "${{ inputs.ssh-key }}" > /home/runner/.ssh/id_rsa
            chmod 600 /home/runner/.ssh/id_rsa
            #ssh-agent -a /tmp/ssh_agent.sock > /dev/null
            #ssh-add /home/runner/.ssh/id_rsa

      - name: Env variables REPO_OWNER and REPO_URL
        shell: bash
        run: |
          echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "REPO_URL=${{ github.event.repository.url }}" >> $GITHUB_ENV

      - name: Call Remote Init Script
        shell: bash
        run: |
          ssh -i /home/runner/.ssh/id_rsa ${{ inputs.server-username }}@${{ inputs.server-host }} "bash -s" < ${{ github.action_path }}/init.sh $REPO_OWNER $REPO_URL ${{ inputs.server-host }} ${{ inputs.user-email }}
          scp -i /home/runner/.ssh/id_rsa ${{ github.action_path }}/nginx.conf ${{ inputs.server-username }}@${{ inputs.server-host }}:~/nginx.conf
          scp -i /home/runner/.ssh/id_rsa ${{ github.action_path }}/deploy.sh ${{ inputs.server-username }}@${{ inputs.server-host }}:~/deploy.sh
      
      - name: Call Remote Deploy Script
        shell: bash
        run: ssh -i /home/runner/.ssh/id_rsa ${{ inputs.server-username }}@${{ inputs.server-host }} "bash -s" < ${{ github.action_path }}/deploy.sh $REPO_OWNER $REPO_URL
