# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
env:
  REPO_OWNER: ${{ github.repository_owner }}
  REPO_NAME: ${{ github.repository }}
inputs:
  github-user:  # id of input
    description: 'Username of owner for the repo in which this Action is used.'
    required: true
    default: ''
  repo-name:  # id of input
    description: 'The name of the repo in which this Action is used.'
    required: true
    default: ''
  server-name:  # id of input
    description: 'The domain name of the server to setup.'
    required: true
    default: ''
  user-email:  # id of input
    description: 'An email that will be used to request an https certificate.'
    required: true
    default: ''
  server-user:  # id of input
    description: 'The username used to connect to the server.'
    required: true
    default: 'root'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ REPO_OWNER }}
    - ${{ REPO_NAME }}
    - ${{ inputs.server-name }}
    - ${{ inputs.user-email }}
    - ${{ inputs.server-user }}
