# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  server-username:  # id of input
    description: 'The username used to connect to the server.'
    required: false
    default: 'root'
  server-host:  # id of input
    description: 'The domain name of the server to setup.'
    required: true
    default: ''
  user-email:  # id of input
    description: 'An email that will be used to request an https certificate.'
    required: true
    default: ''
  ssh-key:  # id of input
    description: 'Private ssh key.'
    required: true
    default: ''
runs:
  using: "composite"
  steps:
  
      - uses: actions/checkout@v4
      
      - name: Add Known Host and SSH Key File
        shell: bash
        run: |
            mkdir .ssh
            #ssh-keyscan ${{ inputs.server-name }} >> .ssh/known_hosts
            echo "value" >> .ssh/known_hosts
            echo "${{ inputs.ssh-key }}" > .ssh/id_rsa

      - name: Env variables REPO_OWNER and REPO_URL
        run: |
          echo "REPO_OWNER=${{ github.repository_owner }}" >> $GITHUB_ENV
          echo "REPO_URL=${{ github.event.repository.url }}" >> $GITHUB_ENV
          
      #- name: Call Remote Init Script
      #   shell: bash
      #  run: ssh -i .ssh/id_rsa ${{ inputs.server-user }}@${{ inputs.server-name }} "bash -s" < init.sh $REPO_OWNER $REPO_URL ${{ inputs.server-name }} ${{ inputs.user-email }}
        
      #- name: Call Remote Deploy Script
      #   shell: bash
      #  run: ssh -i .ssh/id_rsa ${{ inputs.server-user }}@${{ inputs.server-name }} "bash -s" < deploy.sh $REPO_OWNER $REPO_URL

