on: [push]

jobs:
  hello_world_job:
    
    runs-on: ubuntu-latest
    name: A job to say hello
    
    steps:
      - name: Hello world action step
        id: hello
        uses: strawstack/ssh-node-server-setup@main
        with:
          server-host: ${{ secrets.serverhost }}
          user-email: ${{ secrets.useremail }}
          ssh-key: ${{ secrets.sshkey }}
