on: []

jobs:
  deploy_server_job:
    
    runs-on: ubuntu-latest
    name: A job to setup an Ubuntu 22 LTS Server and Deploy a Node JS App. 
    
    steps:
      - name: Deploy Server Step
        uses: strawstack/ssh-node-server-setup@main
        with:
          server-host: ${{ secrets.SERVER_HOST }}
          user-email: ${{ secrets.USER_EMAIL }}
          ssh-key: ${{ secrets.SSH_KEY }}
