on: [push]

jobs:
  hello_world_job:
    
    runs-on: ubuntu-latest
    name: A job to say hello
    
    steps:
      - name: Hello world action step
        id: hello
        uses: strawstack/ssh-node-server-setup@main
        with:
          server-name: "something.other.test"
          user-email: "user@email"
          ssh-key: "ssh key from secrets"
